services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      timeout: 10s
      retries: 10

  backend:
    image: ${DOCKER_USERNAME}/swyp10-9-backend:latest
    container_name: swyp10-9-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 데이터베이스 설정
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # 서버 설정
      SERVER_PORT: ${SERVER_PORT}
      
      # JWT 설정
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800}
      
      # 카카오 OAuth 설정
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_PATH: ${KAKAO_REDIRECT_PATH:-/api/auth/kakao-redirect}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_TOKEN_URL: ${KAKAO_TOKEN_URL:-https://kauth.kakao.com/oauth/token}
      KAKAO_USER_INFO_URL: ${KAKAO_USER_INFO_URL:-https://kapi.kakao.com/v2/user/me}
      
      # TourAPI 설정
      TOUR_API_KEY: ${TOUR_API_KEY}
      PAGE_SIZE: ${PAGE_SIZE:-10}
      EVENT_START_DATE: ${EVENT_START_DATE:-20251201}
      EVENT_END_DATE: ${EVENT_END_DATE:-20251201}

    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s