version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      # MariaDB 설정 - root 사용자로 통일
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_HOST: '%'
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/swyp10-9-backend:latest
    container_name: swyp10-9-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # 데이터베이스 설정 - root 사용자로 통일
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}

      # 서버 설정
      SERVER_PORT: 8080

      # JWT 설정
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800}

      # 카카오 OAuth 설정
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_PATH: ${KAKAO_REDIRECT_PATH:-/api/auth/kakao-redirect}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_TOKEN_URL: ${KAKAO_TOKEN_URL:-https://kauth.kakao.com/oauth/token}
      KAKAO_USER_INFO_URL: ${KAKAO_USER_INFO_URL:-https://kapi.kakao.com/v2/user/me}

      # TourAPI 설정
      TOUR_API_KEY: ${TOUR_API_KEY}
      PAGE_SIZE: ${PAGE_SIZE:-10}
      EVENT_START_DATE: ${EVENT_START_DATE:-20250101}
      EVENT_END_DATE: ${EVENT_END_DATE:-20251231}

      # Spring Boot 3.x Feign 설정 (kebab-case)
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT: 15000
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_DEFAULT_READ_TIMEOUT: 60000
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_TOUR_API_CLIENT_CONNECT_TIMEOUT: 20000
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_TOUR_API_CLIENT_READ_TIMEOUT: 90000

      # HTTP 클라이언트 설정
      SPRING_CLOUD_OPENFEIGN_HTTPCLIENT_ENABLED: true
      SPRING_CLOUD_OPENFEIGN_HTTPCLIENT_MAX_CONNECTIONS: 200
      SPRING_CLOUD_OPENFEIGN_HTTPCLIENT_MAX_CONNECTIONS_PER_ROUTE: 50

      # 로그 레벨
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_DEFAULT_LOGGER_LEVEL: basic
      LOGGING_LEVEL_FEIGN_LOGGER: DEBUG

    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s