spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never
      isolation-level-for-create: read_committed
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:swyp10}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   # MariaDBDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: ${SERVER_PORT:8080}

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-must-be-at-least-256-bits-long}
  expiration: ${JWT_EXPIRATION:86400} # 24시간 (초 단위)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800} # 7일 (초 단위)

# OAuth 설정
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
    redirect-path: ${KAKAO_REDIRECT_PATH:/api/auth/kakao-redirect}
    redirect-uri: ${KAKAO_REDIRECT_URI:/api/auth/kakao-redirect}
    token-url: ${KAKAO_TOKEN_URL:https://kauth.kakao.com/oauth/token}
    user-info-url: ${KAKAO_USER_INFO_URL:https://kapi.kakao.com/v2/user/me}

# TourAPI 설정
tourapi:
  service-key: ${TOUR_API_KEY:NYxrwdvbgchC%2BIW35g87NwgQoz%2FoqxwkVYW1O2Ihur8r3%2BH35FIzVQBedsthKFqUOUQ9PthT4hnHxjC4Ijg2cA%3D%3D}
  batch:
    page-size: ${PAGE_SIZE:10}
    festival:
      event-start-date: ${EVENT_START_DATE:20251201}
      event-end-date: ${EVENT_END_DATE:20251201}
    restaurant:
      content-type-id: "39"  # 음식점
      page-size: 100
      max-total-items: 100  # 최대 100개로 제한
    travel-course:
      content-type-id: "25"  # 여행코스
      page-size: 100
      max-total-items: 100   # 100개로 제한

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
  show-enum-schema: true
